language: java
    
jdk:
  - oraclejdk11

addons:
  chrome: beta

services:
  - docker
  
notifications:
  email:
    - angular2guy@gmx.ch
  on_success: always
  on_failure: always

before_install:
  - nvm install 14.15
  - nvm use 14.15

      
script:
  mvn clean install -Ddocker=true
